
name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment only when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Match your Django project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run Django tests
      #   run: |
      #     python manage.py test

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pip install awsebcli
          eb init f1-dashboard \
            --platform python-3.11 \
            --region $AWS_REGION
          # Check if environment exists, create if it doesn't
          if ! eb list | grep -q f1-dashboard-env-vmistry; then
            eb create f1-dashboard-env-vmistry \
              --platform python-3.11 \
              --instance-type t2.micro \
              
          fi
          eb deploy f1-dashboard-env-vmistry
